---
# tasks file for manage-spamassassin
- name: install spamassassin
  package:
    name: spamassassin
    state: present

- name: set postfix in soft_bounce mode
  command: /usr/sbin/postconf soft_bounce=yes

- name: copy spam score file
  copy: 
     src: etc/spamassassin/z_d7031.cf
     dest: /etc/spamassassin/
     backup: yes
     mode: 644
     owner: root
     group: root
     validate: 'spamassassin --lint %s'
  notify: reload spamassassin service
